from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional, List
import os
import openai

# -------------------------------------------------------------------
# Setup
# -------------------------------------------------------------------
router = APIRouter()
openai.api_key = os.getenv("OPENAI_API_KEY")  # Add in Render env vars

# -------------------------------------------------------------------
# Data models
# -------------------------------------------------------------------
class Vehicle(BaseModel):
    make: Optional[str] = None
    model: Optional[str] = None
    year: Optional[int] = None
    mileage_km: Optional[int] = None


class DiagnoseIn(BaseModel):
    text: str                        # <-- frontend sends "text"
    vehicle: Optional[Vehicle] = None


class DiagnoseOut(BaseModel):
    causes: List[str]
    advice: str
    cost_qr_range: str
    safety: Optional[str] = None


# -------------------------------------------------------------------
# Helper – ask GPT-5 if no rule-based match found
# -------------------------------------------------------------------
def ask_gpt(prompt: str) -> dict:
    try:
        response = openai.chat.completions.create(
            model="gpt-4o",   # or "gpt-5" when available in your account
            messages=[
                {"role": "system", "content": "You are an automotive diagnostic assistant that helps identify car problems."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.4
        )

        reply = response.choices[0].message.content.strip()
        return {
            "causes": [reply],
            "advice": "Recommendation generated by AI analysis.",
            "cost_qr_range": "Estimate varies — further inspection required.",
            "safety": "Consult a qualified technician soon."
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"GPT request failed: {str(e)}")


# -------------------------------------------------------------------
# Diagnose endpoint
# -------------------------------------------------------------------
@router.post("/diagnose", response_model=DiagnoseOut)
def diagnose(body: DiagnoseIn):
    try:
        txt = body.text.lower()
        causes, advice, safety, cost = [], "", None, "QAR 150–350"

        # --- Local rule-based quick matches ---
        if "brake" in txt or "squeal" in txt:
            causes = ["Worn brake pads", "Glazed rotors"]
            advice = "Inspect pads & rotors; replace if worn."
            safety = "Service soon — reduced braking performance."
            cost = "QAR 300–900"

        elif "overheat" in txt:
            causes = ["Coolant leak", "Thermostat stuck", "Radiator fan issue"]
            advice = "Check coolant, thermostat, and fan operation."
            safety = "Stop driving if temperature keeps rising."
            cost = "QAR 250–1200"

        elif "start" in txt or "starting" in txt:
            causes = ["Weak battery", "Starter motor issue", "Ignition system fault"]
            advice = "Check battery charge, starter, and ignition."
            safety = "If engine won’t start, seek roadside help."
            cost = "QAR 200–1000"

        else:
            # --- Fallback to GPT if not found ---
            gpt_result = ask_gpt(
                f"Vehicle info: {body.vehicle}. "
                f"User reported problem: {body.text}. "
                f"Suggest possible causes, safety notes, and repair advice in bullet format."
            )
            return DiagnoseOut(**gpt_result)

        return DiagnoseOut(
            causes=causes,
            advice=advice,
            cost_qr_range=cost,
            safety=safety
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": str(e)})
